<SplashScreen>:
    BoxLayout:
        orientation: 'vertical'

        CircularImageStencil:
            id: logo
            source: "assets/logo.png"
            size_hint: 0.5, 0.5
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            opacity: 0


<CircularImageStencil@StencilView>:
    source: ""  # Add this so KV knows about the property
    Image:
        source: root.source
        size: root.size
        pos: root.pos
